{% set name = "azure-mgmt-compute" %}
{% set version = "29.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-compute-{{ version }}.zip
  sha256: 2d5a1bae7f5d307ca1e850d7e83fed9c839d4f635b10a4b8d3f8bc6098ac2888

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - azure-common >=1.1,<1.2.0
    - azure-mgmt-core >=1.3.1,<2.0.0
    - msrest >=0.6.21

test:
  imports:
    - azure.mgmt.compute
    - azure.mgmt.compute.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Compute Management Client Library for Python
  license: MIT
  license_file:
    - LICENSE
  description: |
    This is the Microsoft Azure Compute Management Client Library. 
    This package has been tested with Python 3.6+. For a more complete 
    view of Azure libraries, see the [azure sdk python release](https://aka.ms/azsdk/python/all).

    To learn how to use this package, see the [quickstart guide](https://aka.ms/azsdk/python/mgmt).

    PyPI: [https://pypi.org/project/azure-mgmt-compute/](https://pypi.org/project/azure-mgmt-compute/)

  doc_url: https://azure.github.io/azure-sdk-for-python
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - Maxyme
    - sugatoray
