schema_version: 1

context:
  name: azure-mgmt-compute
  version: 34.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: cd9d35d1cc1b8cb0bd241ad55c91b77d14e04ae73c632ada1140135f9c217fe1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1
    - typing-extensions >=4.6.0

tests:
  - python:
      imports:
        - azure.mgmt.compute
        - azure.mgmt.compute.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Compute Management Client Library for Python
  license: MIT
  license_file:
    - LICENSE
  description: |
    This is the Microsoft Azure Compute Management Client Library.
    This package has been tested with Python 3.6+. For a more complete
    view of Azure libraries, see the [azure sdk python release](https://aka.ms/azsdk/python/all).

    To learn how to use this package, see the [quickstart guide](https://aka.ms/azsdk/python/mgmt).

    PyPI: [https://pypi.org/project/azure-mgmt-compute/](https://pypi.org/project/azure-mgmt-compute/)

  homepage: https://github.com/Azure/azure-sdk-for-python
  repository: https://github.com/Azure/azure-sdk-for-python
  documentation: https://azure.github.io/azure-sdk-for-python

extra:
  recipe-maintainers:
    - Maxyme
    - sugatoray
    - janjagusch
